name: Build & Deploy
on:
  push:
    branches: [master]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy React App
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} #ip of the server we ssh into
          key: ${{secrets.SSH_KEY}} #private key of the server 
          username: ${{secrets.SSH_USERNAME}} # user on the server we are sshing into
          passphrase: ${{secrets.SSH_PASSPHRASE}} # ssh key passphrase
          # This script is inefficient because we are just re-installing every commit. That's very bad, but for now I just want to get this working
          # We can figure it out later
          script: |
            cd /home
            rm -rf trivia
            git clone https://github.com/greelz/trivia.git
            cd trivia
            npm install 
            npm run build
            cp -r build/* /var/www/trivia/html
            echo 'Deployment successful to digital ocean'